services: 
    webapi:
        #image: registry.neftm.local/ldap
        build:
            # set path to source code project directory
            context: src/presentation/KutCode.Security.Ldap.WebApi
        ports: 
            - 9080:80
            - 9443:443
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            ListenPort: 9088
        volumes:
          - ./appsettings:/app/appsettings
          - ./logs:/app/logs